---
- name: include the roles
  include_role:
    apply:
      become: true
    name: "{{ item }}"
  loop:
    - geosword.ws-base
    - grog.user
    - grog.authorized-key

- name: copy in my id_rsa
  copy:
    src: "{{ lookup('env','HOME') }}/.ssh/id_rsa"
    dest: "{{ user_home }}/.ssh/id_rsa"
    mode: '0600'
    owner: "{{ user_name }}"
    group: "{{ user_group }}"
  become: true
