# If you tag your "include_role" and there is more than one, you can skip specific roles with:
# $ ANSIBLE_SKIP_TAGS="geerlingguy.nginx,geerlingguy.php" molecule converge
---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:

    - name: "Include the role you are developing here"
      include_role:
        apply:
          become: true
        name: "ansible-role-ws-base"
