# If you tag your "include_role" and there is more than one, you can skip specific roles with:
# $ ANSIBLE_SKIP_TAGS="geerlingguy.nginx,geerlingguy.php" molecule converge
---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:

- import_playbook: ../../playbook.yml
