# If you tag your "include_role" and there is more than one, you can skip specific roles with:
# $ ANSIBLE_SKIP_TAGS="geerlingguy.nginx,geerlingguy.php" molecule converge
---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: include the playbook vars
      include_vars:
        dir: ../../host_vars/dylans-arch/
        extensions:
          - yml

    - name: import the main play
      include_tasks: ../../playbook_tasks.yml
